### ISSUE TITLE
Compass Heading receive error on Android 14

### ISSUE THREAD

**Issue by iBog** [dariocavada/ar_location_viewer#1]
PlatformException(error, To use the sampling rate of 500 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS., null, null),

with added to AndroidManifest.xml
`<uses-permission android:name="android.permission.HIGH_SAMPLING_RATE_SENSORS"/>`
all working fine

**Comment by dariocavada** [comment]
Thank you, added to the readme.md
